# Generated by Django 5.2.4 on 2025-07-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_description_movie_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
